### ISSUE TITLE
Program crashes when trying to fetch the data

### ISSUE THREAD

**Issue by 2xD2D** [hyperfield/yt-channel-downloader#14]
Everytime you press on fetch, the program loads for a moment, and then closes itself

**Comment by hyperfield** [comment]
Please let me know about the following so that I could better understand the problem:

1. Your operating system.
2. Does the previous version of the app work (you can find it in Releases here)?
3. Does your country block or slow down YouTube?

**Comment by 2xD2D** [comment]
I am able to answer the first and last question. but because I'm not home at the moment, you will need to wait for the answer to the third question.

1. Win 11
3. No. I live in Germany and I have never heard that they slow down YouTube.

**Comment by hyperfield** [comment]
Thank you for the feedback, I'm looking forward to your answer to the second question.

**Comment by 2xD2D** [comment]
does the problem maybe has something to do with the reason I have my settings set to "dowload audio only"?

**Comment by digifjord** [comment]
Not likely. Can you please try the previous version of the app? This would help me narrow down the scope of troubleshooting.

**Comment by digifjord** [comment]
So it appears that recent changes on YouTube caused this problem, and there was also a bug with the "Any" format. I have fixed both issues.

You can use the updated app by cloning the repository. However, the fixed version is not yet available as an installer for Windows, as I'm planning to make a few more improvements and possibly use a different packaging method.

Please let me know if it works for you now.

**Comment by hyperfield** [comment]
So it appears that recent changes on YouTube caused this problem, and there was also a bug with the "Any" format. I have fixed both issues.

You can use the updated app by cloning the repository. However, the fixed version is not yet available as an installer for Windows, as I'm planning to make a few more improvements and possibly use a different packaging method.

Please let me know if it works for you now.
