### ISSUE TITLE
Fetch Request Crash

### ISSUE THREAD

**Issue by Kirthbongar** [hyperfield/yt-channel-downloader#15]
Hello I am running windows 11 and just attempted to use the application. for the first video it seems like it tried to download the video and then partialy through it crashed. Now when I attempt to fetch a video it just immediately crashes. Here is the error I am getting. I am running the CMD as administrator. I did change the download type to MP4 and changed the download location.After changing the video format from .MP4 back to any it is now working. I am successfully downloading videos in MP4 format even though the fomat radial drop down is set to Any. Hope this helps with future troubleshooting.

 File "d:\Documents\yt-channel-downloader\.venv\Lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=dhk2WU506Uc. Please file a bug report at https://github.com/pytube/pytube

(.venv) d:\Documents\yt-channel-downloader>

**Comment by digifjord** [comment]
Hi,

Thank you for opening this issue. Recent changes on YouTube caused this problem, and there was also a bug with the "Any" format. I have fixed both issues.

You can use the updated app by cloning the repository. However, the fixed version is not yet available as an installer for Windows, as I'm planning to make a few more improvements and possibly use a different packaging method.

Please let me know if it works for you now.

**Comment by hyperfield** [comment]
Hi,

Thank you for opening this issue. Recent changes on YouTube caused this problem, and there was also a bug with the "Any" format. I have fixed both issues.

You can use the updated app by cloning the repository. However, the fixed version is not yet available as an installer for Windows, as I'm planning to make a few more improvements and possibly use a different packaging method.

Please let me know if it works for you now.

**Comment by hyperfield** [comment]
Version 0.4.2 is out and the installer for Windows is also available in [Releases](https://github.com/hyperfield/yt-channel-downloader/releases).
