### ISSUE TITLE
Sign in to confirm your age. This video may be inappropriate for some users

### ISSUE THREAD

**Issue by amakuhin** [hyperfield/yt-channel-downloader#6]
Hello,

I get this error on some videos, and after getting 4 of such errors, download stops. Is there any way to overcome this error. As far as I know, there's a solution to change something in pytube, but this works not for all cases

Here is the error info (I've deleted code of real video and replaced it with <video_code>):

> WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> ERROR: [youtube] <video_code>: Sign in to confirm your age. This video may be inappropriate for some users.
> Traceback (most recent call last):
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in wrapper
>     return func(self, *args, **kwargs)
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1702, in __extract_info
>     ie_result = ie.extract(url)
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract
>     ie_result = self._real_extract(url)
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\youtube.py", line 4176, in _real_extract
>     self.raise_no_formats(reason, expected=True)
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 1193, in raise_no_formats
>     raise ExtractorError(msg, expected=expected, video_id=video_id)
> yt_dlp.utils.ExtractorError: [youtube] <video_code>: Sign in to confirm your age. This video may be inappropriate for some users.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\Projects\yt_dl\1\yt-channel-downloader\classes\mainwindow.py", line 157, in run
>     closest_format_id = get_video_format_details(
>   File "E:\Projects\yt_dl\1\yt-channel-downloader\classes\utils.py", line 82, in get_video_format_details
>     video_info = ydl.extract_info(url, download=False)
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1556, in extract_info
>     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1585, in wrapper
>     self.report_error(str(e), e.format_traceback())
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1045, in report_error
>     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
>   File "C:\Users\amaku\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 984, in trouble
>     raise DownloadError(message, exc_info)
> yt_dlp.utils.DownloadError: ERROR: [youtube] <video_code>: Sign in to confirm your age. This video may be inappropriate for some users.

Here is what I got for pytube issue fix: https://stackoverflow.com/questions/75791765/how-to-download-videos-that-require-age-verification-with-pytube

**Comment by hyperfield** [comment]
Hello,
Thanks for posting this. This is not a bug except for the absence of graceful handling of the exception. This is a lack of a feature, which requires implementation of support for Youtube account sign-in. This feature is currently being developed and will be added in the next release (this month or next).

**Comment by hyperfield** [comment]
This feature has been implemented and is currently available in the development branch. It will soon be available in the production branch as well.
