### ISSUE TITLE
Different errors using Windows 10 (HTTP Error 400, Prediction check failed, ffmpeg not installed)

### ISSUE THREAD

**Issue by arkinson9** [hyperfield/yt-channel-downloader#8]
I am trying to use the latest v.0.3.3 on a Windows 10 machine.

1. GUI starts well,
2. Fetching a channel works fine
3. Starting "Download" generates the following errors (no matter witch setting I try to use):

`E:\yt-channel-downloader>.venv\Scripts\activate.bat

(.venv) E:\yt-channel-downloader>python main.py
[youtube] Extracting URL: https://www.youtube.com/watch?v=tMELP9XuFSg
[youtube] tMELP9XuFSg: Downloading webpage
[youtube] tMELP9XuFSg: Downloading ios player API JSON
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] tMELP9XuFSg: Downloading player 8d9f6215
WARNING: [youtube] tMELP9XuFSg: nsig extraction failed: You may experience throttling for some formats
         n = uXMooCK1GzQlXUGS0bV ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
WARNING: [youtube] tMELP9XuFSg: nsig extraction failed: You may experience throttling for some formats
         n = 2k6l10UYqDDyUtMXfla ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
[youtube] tMELP9XuFSg: Downloading m3u8 information
[youtube] Extracting URL: https://www.youtube.com/watch?v=tMELP9XuFSg
[youtube] tMELP9XuFSg: Downloading webpage
[youtube] tMELP9XuFSg: Downloading ios player API JSON
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] tMELP9XuFSg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] tMELP9XuFSg: Downloading player 8d9f6215
WARNING: [youtube] tMELP9XuFSg: nsig extraction failed: You may experience throttling for some formats
         n = ZgqrBDhIyMlVKIEaKUH ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
WARNING: [youtube] tMELP9XuFSg: nsig extraction failed: You may experience throttling for some formats
         n = MMIWFMOXgScV23kjC3L ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
[youtube] tMELP9XuFSg: Downloading m3u8 information
[info] tMELP9XuFSg: Downloading 1 format(s): 232+140
ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
Traceback (most recent call last):
  File "E:\yt-channel-downloader\classes\mainwindow.py", line 193, in run
    ydl.download([self.url])
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3510, in download
    self.__download_wrapper(self.extract_info)(
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3485, in wrapper
    res = func(*args, **kwargs)
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 3345, in process_info
    self.report_error(f'{msg}. Aborting due to --abort-on-error')
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "E:\yt-channel-downloader\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 984, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error`

**Comment by hyperfield** [comment]
Thanks for reporting this. You need to download ffmpeg from https://ffmpeg.org/download.html and install it on Windows. I'll add a note to the README.
